* Open Library API                                                                   :verb:
# Open Library has developed a suite of APIs to help developers get up
# and running with our data. We encourage interested developers to
# join the ol-tech mailing list to stay up-to-date with the latest
# news, or dive in with our own development team at our bug tracker or
# our GitHub source code repository.

# Open Library has a RESTful API, best used to link into Open Library
# data in JSON, YAML and RDF/XML. There's also an earlier JSON API,
# which is deprecated now. This is only retained for backward
# compatibility.

# From: https://openlibrary.org/developers/api

template http://openlibrary.org
User-Agent: Verb/Emacs Emacs/{{emacs-version}}
Accept: application/json

** Search
# Open Library provides an experimental API to search.
template /search.json

*** By Title
get ?title={{(read-string "Title: ")}}

*** By Author
get ?author={{(read-string "Author: ")}}

** Books
:properties:
:Verb-Store: book
:end:
# The API allows requesting information on one or more books using
# ISBNs, OCLC Numbers, LCCNs and OLIDs (Open Library IDs).

#+BEGIN_SRC verb :wrap src ob-verb-response
get /api/books?bibkeys=ISBN:{{(verb-var isbn)}}&format=json
#+END_SRC

#+RESULTS:
#+BEGIN_src ob-verb-response
HTTP/1.1 200 OK
Server: nginx/1.4.6 (Ubuntu)
Date: Tue, 28 Jan 2020 21:15:49 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Method: GET, OPTIONS
Access-Control-Max-Age: 86400
X-OL-Stats: "IB 1 0.062 MC 1 0.002 TT 0 0.066"

{
  "ISBN:9780465026562": {
    "bib_key": "ISBN:9780465026562",
    "preview": "noview",
    "thumbnail_url": "https://covers.openlibrary.org/b/id/8148459-S.jpg",
    "preview_url": "http://openlibrary.org/books/OL26435358M/Gödel_Escher_Bach_an_eternal_golden_braid",
    "info_url": "http://openlibrary.org/books/OL26435358M/Gödel_Escher_Bach_an_eternal_golden_braid"
  }
}
#+END_src
